# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('data_source', models.CharField(max_length=255, verbose_name='Data source')),
                ('account_id', models.CharField(max_length=255, verbose_name='Account ID')),
                ('upload_file', models.FileField(blank=True, default=None, upload_to='ga_uploads', verbose_name='Upload file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GA session',
                'verbose_name_plural': 'GA session',
            },
        ),
    ]
