# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'Data source', 'verbose_name_plural': 'Data source'},
        ),
        migrations.AddField(
            model_name='datasource',
            name='provider',
            field=models.CharField(blank=True, default='Google Analytics', max_length=255, verbose_name='Data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='account_id',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_source',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
