# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_auto_20170503_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='title',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_source',
            field=models.CharField(default=None, max_length=255, verbose_name='Data source'),
        ),
    ]
