# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0003_auto_20170504_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='data_source',
        ),
        migrations.AddField(
            model_name='datasource',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Data Source Name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='provider',
            field=models.CharField(blank=True, default='Google Analytics', max_length=255, verbose_name='Provider'),
        ),
    ]
