# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0004_auto_20170504_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Google Analytics', max_length=255, verbose_name='Provider Title')),
                ('name', models.CharField(blank=True, default='Google Analytics', max_length=255, verbose_name='Provider Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='provider',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='upload_file',
            field=models.FileField(blank=True, default=None, upload_to='file_uploads', verbose_name='Upload file'),
        ),
    ]
