# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_loader', '0007_dataprovider_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFlowSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_interval', models.SmallIntegerField(choices=[(1, '30 min'), (2, '1 hour'), (3, '2 hours'), (4, '5 hours'), (5, '10 hours'), (6, '24 hours')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
