# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0008_dataflowsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflowsettings',
            name='sync_interval',
            field=models.SmallIntegerField(choices=[(1, '30 min'), (2, '1 hour'), (3, '2 hours'), (4, '5 hours'), (5, '10 hours'), (6, '24 hours')], default=1),
        ),
    ]
