# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0009_auto_20170512_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflowsettings',
            name='sync_interval',
            field=models.SmallIntegerField(choices=[(1, '30 minutes'), (2, '1 hour'), (3, '2 hours'), (4, '5 hours'), (5, '10 hours'), (6, '24 hours')], default=1),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='account_id',
            field=models.CharField(default=None, max_length=255, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='upload_file',
            field=models.FileField(default=None, upload_to='file_uploads', verbose_name='Upload file'),
        ),
    ]
