# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0011_datasource_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='document_url',
            field=models.CharField(blank=True, default=None, max_length=355, null=True, verbose_name='Document URL'),
        ),
    ]
