# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0015_auto_20170608_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('account_id', models.CharField(default=None, max_length=255, verbose_name='Account ID')),
                ('upload_file', models.FileField(default=None, upload_to='file_uploads', verbose_name='Upload file')),
                ('dimensions', models.CharField(blank=True, max_length=355, null=True, verbose_name='Analytics dimensions')),
                ('metrics', models.CharField(blank=True, max_length=355, null=True, verbose_name='Analytics metrics')),
            ],
            options={
                'verbose_name_plural': 'Google Analytics Data source',
                'verbose_name': 'Google Analytics Data source',
            },
            bases=('data_loader.datasource',),
        ),
    ]
