# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0016_analyticsdatasource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsdatasource',
            name='document_url',
        ),
        migrations.AlterField(
            model_name='analyticsdatasource',
            name='account_id',
            field=models.CharField(default=None, max_length=255, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='analyticsdatasource',
            name='dimensions',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Analytics dimensions'),
        ),
        migrations.AlterField(
            model_name='analyticsdatasource',
            name='metrics',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Analytics metrics'),
        ),
        migrations.AlterField(
            model_name='analyticsdatasource',
            name='upload_file',
            field=models.FileField(default=None, upload_to='file_uploads', verbose_name='Upload file'),
        ),
    ]
