# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0017_spreadsheetsdatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsdatasource',
            name='dimensions',
            field=models.CharField(default=None, max_length=355, verbose_name='Analytics dimensions'),
        ),
        migrations.AlterField(
            model_name='analyticsdatasource',
            name='metrics',
            field=models.CharField(default=None, max_length=355, verbose_name='Analytics metrics'),
        ),
    ]
