# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0019_spreadsheetsdatasource_field_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgreSQLDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.CharField(max_length=255, verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('database', models.CharField(max_length=255, verbose_name='Database')),
                ('schema_file', models.FileField(default=None, upload_to='file_uploads', verbose_name='Upload file')),
            ],
            options={
                'verbose_name': 'PostgreSQL Data source',
                'verbose_name_plural': 'PostgreSQL Data sources',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.AlterModelOptions(
            name='analyticsdatasource',
            options={'verbose_name': 'Google Analytics Data source', 'verbose_name_plural': 'Google Analytics Data sources'},
        ),
        migrations.AlterModelOptions(
            name='spreadsheetsdatasource',
            options={'verbose_name': 'Spreadsheets Data source', 'verbose_name_plural': 'Spreadsheets Data sources'},
        ),
    ]
