# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0021_auto_20170626_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verticadatasource',
            name='schema_name',
            field=models.CharField(max_length=255, verbose_name='Schema name'),
        ),
    ]
