# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0022_auto_20170626_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCloudDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('bucket', models.CharField(max_length=255, verbose_name='Bucket')),
                ('paths', models.CharField(max_length=255, verbose_name='Paths')),
                ('account_email', models.CharField(max_length=255, verbose_name='Account email')),
                ('private_key', models.FileField(default=None, upload_to='file_uploads', verbose_name='Private key')),
                ('app_name', models.CharField(max_length=255, verbose_name='Application name')),
            ],
            options={
                'verbose_name': 'GoogleCloud Data source',
                'verbose_name_plural': 'GoogleCloud Data sources',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='HadoopDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('path', models.CharField(max_length=255, verbose_name='File path on OS')),
                ('os_config_file', models.FileField(default=None, upload_to='file_uploads', verbose_name='OS config file')),
                ('os_config_params', models.CharField(max_length=255, verbose_name='Config file parameters')),
                ('log_level', models.CharField(max_length=255, verbose_name='Logging level')),
            ],
            options={
                'verbose_name': 'Hadoop Data source',
                'verbose_name_plural': 'Hadoop Data sources',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='MarketoDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('endpoint', models.CharField(max_length=255, verbose_name='SOAP endpoint URL')),
                ('account_id', models.FileField(default=None, upload_to='file_uploads', verbose_name='User ID')),
                ('key_file', models.FileField(default=None, upload_to='file_uploads', verbose_name='Encryption key')),
                ('start_time', models.CharField(max_length=255, verbose_name='Fetch leads start time')),
            ],
            options={
                'verbose_name': 'Marketo Data source',
                'verbose_name_plural': 'Marketo Data sources',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='SalesforceDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Login endpoint')),
                ('sf_object', models.CharField(max_length=255, verbose_name='API object name')),
            ],
            options={
                'verbose_name': 'Salesforce Data source',
                'verbose_name_plural': 'Salesforce Data sources',
            },
            bases=('data_loader.datasource',),
        ),
    ]
