# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0023_googleclouddatasource_hadoopdatasource_marketodatasource_salesforcedatasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamoDBDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.CharField(max_length=255, verbose_name='Port')),
                ('access_key', models.CharField(max_length=255, verbose_name='Access key')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Secret key')),
                ('database', models.CharField(max_length=255, verbose_name='Database name')),
                ('region', models.CharField(max_length=255, verbose_name='Region name')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint URl')),
                ('table', models.CharField(max_length=255, verbose_name='Table name')),
            ],
            options={
                'verbose_name_plural': 'DynamoDB Data sources',
                'verbose_name': 'DynamoDB Data source',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='HTTPDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('url', models.CharField(max_length=255, verbose_name='Base URL')),
                ('method', models.CharField(max_length=255, verbose_name='HTTP method')),
                ('params', models.CharField(max_length=255, verbose_name='Query params')),
            ],
            options={
                'verbose_name_plural': 'HTTP Data sources',
                'verbose_name': 'HTTP Data source',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='TwitterDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('account_id', models.CharField(max_length=255, verbose_name='Twitter user ID')),
                ('archive_id', models.CharField(max_length=255, verbose_name='Archive/Feed ID')),
                ('archive_link', models.CharField(max_length=255, verbose_name='Archive/Feed Public Link')),
            ],
            options={
                'verbose_name_plural': 'Twitter Data sources',
                'verbose_name': 'Twitter Data source',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='ZendeskDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('login_url', models.CharField(max_length=255, verbose_name='Login URL')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('target', models.CharField(max_length=255, verbose_name='Source target type')),
            ],
            options={
                'verbose_name_plural': 'Zendesk Data sources',
                'verbose_name': 'Zendesk Data source',
            },
            bases=('data_loader.datasource',),
        ),
    ]
