# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0025_amazons3datasource_mysqldatasource_redshiftdatasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('uri', models.CharField(max_length=255, verbose_name='JIRA API endpoint')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('jql', models.CharField(max_length=255, verbose_name='JQL')),
                ('columns', models.CharField(max_length=255, verbose_name='Issue attributes')),
            ],
            options={
                'verbose_name_plural': 'Jira Data sources',
                'verbose_name': 'Jira Data source',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='MixpanelDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('key', models.CharField(max_length=255, verbose_name='Project API Key')),
                ('secret', models.CharField(max_length=255, verbose_name='Project API Secret')),
                ('timezone', models.CharField(max_length=255, verbose_name='Project timezone')),
            ],
            options={
                'verbose_name_plural': 'Mixpanel Data sources',
                'verbose_name': 'Mixpanel Data source',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='MSSQLDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.CharField(max_length=255, verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('database', models.CharField(max_length=255, verbose_name='Database')),
                ('instance', models.CharField(max_length=255, verbose_name='Instance')),
            ],
            options={
                'verbose_name_plural': 'MSSQL Data sources',
                'verbose_name': 'MMSSQL Data source',
            },
            bases=('data_loader.datasource',),
        ),
    ]
