# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0026_jiradatasource_mixpaneldatasource_mssqldatasource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiradatasource',
            old_name='columns',
            new_name='issue_columns',
        ),
    ]
