# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0027_auto_20170628_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.CharField(max_length=255, verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('path_prefix', models.CharField(max_length=255, verbose_name='Path prefix')),
                ('passphrase', models.CharField(max_length=255, verbose_name='Passphrase')),
                ('secret_key', models.FileField(default=None, upload_to='file_uploads', verbose_name='Secret key file')),
            ],
            options={
                'verbose_name_plural': 'SFTP Data sources',
                'verbose_name': 'SFTP Data source',
            },
            bases=('data_loader.datasource',),
        ),
        migrations.CreateModel(
            name='TeradataDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('database', models.CharField(max_length=255, verbose_name='Database')),
            ],
            options={
                'verbose_name_plural': 'Teradata Data sources',
                'verbose_name': 'Teradata Data source',
            },
            bases=('data_loader.datasource',),
        ),
    ]
