# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0028_sftpdatasource_teradatadatasource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sftpdatasource',
            old_name='path_prefix',
            new_name='prefix',
        ),
    ]
