# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0030_adwordsdatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adwordsdatasource',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Query condition list'),
        ),
    ]
