# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0031_auto_20170706_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparkPostDataSource',
            fields=[
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data_loader.DataSource')),
                ('url', models.CharField(max_length=255, verbose_name='URL endpoint')),
                ('api_key', models.CharField(max_length=255, verbose_name='Auth API key')),
            ],
            options={
                'verbose_name_plural': 'SparkPost Data sources',
                'verbose_name': 'SparkPost Data source',
            },
            bases=('data_loader.datasource',),
        ),
    ]
