# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0032_sparkpostdatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkpostdatasource',
            name='api_key',
            field=models.CharField(max_length=500, verbose_name='Auth API key'),
        ),
        migrations.AlterField(
            model_name='sparkpostdatasource',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL endpoint'),
        ),
    ]
