# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0033_auto_20170707_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgresqldatasource',
            name='query',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Query'),
        ),
        migrations.AddField(
            model_name='postgresqldatasource',
            name='select',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Select'),
        ),
        migrations.AddField(
            model_name='postgresqldatasource',
            name='table',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Table name'),
        ),
        migrations.AddField(
            model_name='postgresqldatasource',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Where'),
        ),
        migrations.AlterField(
            model_name='dataflowsettings',
            name='sync_interval',
            field=models.SmallIntegerField(choices=[(2, '30 minutes'), (3, '1 hour'), (4, '2 hours'), (5, '5 hours'), (6, '10 hours'), (7, '24 hours')], default=2),
        ),
    ]
