# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170512_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default=None, max_length=120, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Last name'),
        ),
    ]
