# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170711_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rs_password',
            field=models.CharField(default=None, max_length=120, verbose_name='Output datastorage password'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rs_username',
            field=models.CharField(default=None, max_length=120, verbose_name='Output datastorage username'),
        ),
    ]
