# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170712_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rs_password',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Output datastorage password'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rs_username',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Output datastorage username'),
        ),
    ]
